### PR TITLE
Carla Linux support

### PR DESCRIPTION
**Pull request by arauschert**
Closes https://github.com/arauschert/OSC-ALKS-scenarios/issues/27

Regression test with esmini 2.7.2 successful

### CODE REVIEW

**Comment by jdsika** [comment]
I will test tonight

**Comment by jdsika** [comment]
I am currently trying if it conveniently works with those instructions:

```
# Install required modules Pygame and Numpy
 pip install --user pygame numpy

# There are two different ways to install CARLA

# Debian package installation
# This repository contains CARLA 0.9.10 and later. To install previous CARLA versions, change to a previous version of the docs using the pannel in the bottom right part of the window
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1AF1527DE64CB8D9
sudo add-apt-repository "deb [arch=amd64] http://dist.carla.org/carla $(lsb_release -sc) main"
sudo apt-get update
sudo apt-get install carla-simulator # Install the latest CARLA version or update the current installation
sudo apt-get install carla-simulator=0.9.11 # install a specific CARLA version
cd /opt/carla-simulator
./CarlaUE4.sh
```

**Comment by jdsika** [comment]
I am apparently not able to run Carla in a performant way (lagging like crazy) on my Laptop with Ubunut 20.04....

**Comment by arauschert** [comment]
Regression test with openPASS 0.7 also successful now.

**Review by ArunDas1 — APPROVED** [review]
I also conducted some tests with openPASS and all scenarios work.

**Pull request merged**
